services:
  mongodb:
    image: mongo:5.0.8
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always
    networks:
      - api-network
    #volumes:
    #  - db_data:/var/lib/mongo

  api:
    build:
      context: .
    ports:
      - 80:5000
    environment:
      - FLASK_ENV=development
      - MONGODB_DB=users
      - MONGODB_HOST=mongodb
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./application:/app/application
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  db_data: