services:
  api:
    build:
      labels:
        "name": "api"
      context: .
    container_name: api
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=${FLASK_ENV_DEV}
      - MONGODB_DB=${NAME_DB}
      - MONGODB_HOST=${HOST_DB}
      - MONGODB_USERNAME=${USERNAME_DB}
      - MONGODB_PASSWORD=${PASSWORD_DB}
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./application:/app/application
    networks:
      - api-network

  mongodb:
    image: mongo:5.0.8
    labels:
      "name": "teste" # Utilizado para persistir os dados do mongo e limpar os volumes desnecessários do docker volume
    container_name: mongodb-api
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    restart: always
    networks:
      - api-network
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db

networks:
  api-network:
    driver: bridge

volumes:
  db_data:
    labels:
      "name": "db_data"
