services:
  api:
    build:
      labels:
        "name": "api"
      context: .
    container_name: api
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - MONGODB_DB=users
      - MONGODB_HOST=mongodb
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./application:/app/application
    networks:
      - api-network

  mongodb:
    image: mongo:5.0.8
    labels:
      "name": "teste"
    container_name: mongodb-api
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always
    networks:
      - api-network
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db

networks:
  api-network:
    driver: bridge

volumes:
  db_data:
    labels:
      "name": "db_data"
