# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy Heroku

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setando versao do python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Instalando dependencias
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest mongomock

      - name: test unitarios
        run: make test

  deploy:
    needs: test # Declarando que para esse job ser executado, ele precisa primeiro efetuar os job test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy no Heroku
        run: make heroku
        env:
          HEROKU_API_KEY: ${{ secrets.nome_da_variavel }} # Chamando o valor da variavel configurada no github
          # Essa variavel é utilizada no Heroku para autenticação no cli
